name: taswqly
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash:
  icons_launcher:
  flutter_bloc: ^9.1.1
  icons_plus:
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_svg: ^2.2.0
  google_fonts: ^8.0.2
  dots_indicator: ^4.0.1
  cached_network_image: ^3.4.1
  retrofit: ^4.9.2
  connectivity_plus: ^7.0.0
  json_annotation: ^4.11.0
  retrofit_generator: ^10.2.3
  get_it: ^9.2.1
  injectable: ^2.7.1+4
  logger: ^2.6.2
  pretty_dio_logger: ^1.4.0
  dio: ^5.9.1
  fluttertoast: ^9.0.0
  shared_preferences: ^2.5.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.13.1
  json_serializable: ^6.13.0
  injectable_generator: ^2.12.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/svgs/